# Generated by Django 3.0.3 on 2020-03-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebagApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='cap_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
