# Generated by Django 3.0.3 on 2020-03-13 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rebagApp', '0002_auto_20200303_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rebagApp.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='shipping_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
