# Generated by Django 3.0.3 on 2020-03-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebagApp', '0003_auto_20200313_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
