# Generated by Django 3.0.3 on 2020-03-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebagApp', '0004_auto_20200313_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='raised_by',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='message',
            name='anon_name',
        ),
    ]
