# Generated by Django 3.0.3 on 2020-03-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rebagApp', '0005_auto_20200313_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='rebagApp.Item'),
        ),
    ]
