# Generated by Django 3.0.3 on 2020-03-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rebagApp', '0006_auto_20200313_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='rebagApp.Auction'),
        ),
    ]
