# Generated by Django 3.0.3 on 2020-03-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebagApp', '0007_auto_20200313_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='base_price',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_price',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='message',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
