# Generated by Django 3.0.3 on 2020-03-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebagApp', '0008_auto_20200313_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('1', 'Fair'), ('2', 'Good'), ('3', 'Very Good'), ('4', 'Great'), ('5', 'Excellent'), ('6', 'Pristine')], default='1', max_length=1),
        ),
    ]
